config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import (
    AddDonationView,
    LandingPageView,
    get_institutions,
    get_institutions_api,
    add_donation,
    form_confirmation,
    switch_is_taken,
)

app_name = "home"

urlpatterns = [
    path("", LandingPageView.as_view(), name="home"),
    path("form/", AddDonationView.as_view(), name="form"),
    path("institutions/", get_institutions),
    path("institutions.json", get_institutions_api),
    path("add-donation/", add_donation),
    path("form-confirmation/", form_confirmation),
    path("is-taken/", switch_is_taken),
]

users/urls.py
from django.urls import path

from .views import LoginView, RegisterView, logout_view, account_detail

app_name = "users"

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("settings/", RegisterView.as_view(), name="settings"),
    path("account-detail/", account_detail, name="account-detail"),
]

templates/partials/footer.html
{% load static %}

<footer>
    <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
        </form>
    </div>
    <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
        </div>
    </div>
</footer>

templates/partials/nav.html
{% load static %}

<nav class="container container--70">
  <ul class="nav--actions">
    {% if user.is_authenticated %}
      <li class="logged-user">
        Witaj {{ user.first_name }}
        <ul class="dropdown">
          <li><a href="{% url 'users:account-detail' %}">Profil</a></li>
          <li><a href="{% url 'users:settings' %}">Ustawienia</a></li>
          {% if user.is_superuser %}
            <li><a href="/admin/">Panel administracyjny</a></li>
          {% endif %}
          <li><a href="{% url 'users:logout' %}">Wyloguj</a></li>
        </ul>
      </li>
    {% else %}
      <li><a href="{% url 'users:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
      <li><a href="{% url 'users:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
    {% endif %}
  </ul>

  <ul>
    <li><a href="/" class="btn btn--without-border active">Start</a></li>
    <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
    <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
    <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
    <li><a href="/form/" class="btn btn--without-border">Przekaż dary</a></li>
    <li><a href="/#contact" class="btn btn--without-border">Kontakt</a></li>
  </ul>
</nav>